/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import controller.ControllerUI;
import domain.Article;
import forms.util.FormViewMode;
import javax.swing.JOptionPane;
import forms.validator.Validator;

/**
 *
 * @author Veljko
 */
public class ArticleForm extends javax.swing.JFrame {

    private Article chosenArticle;
    private String error;
    
    /**
     * Creates new form ArticleForm
     */
    public ArticleForm(int formMode) {
        initComponents();
        prepareView(formMode);
        setLocationRelativeTo(null);
        error="";
    }
    
    public ArticleForm(int formMode, Article article) {
        chosenArticle=article;
        initComponents();
        prepareView(formMode);
        setArticle();
        setLocationRelativeTo(null);
        error="";
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboType = new javax.swing.JComboBox<>();
        btnChange = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Artikal");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Naziv:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Cena:");

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tip:");

        comboType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Odeca", "Obuca", "Oprema", "Lopte", "Torbe", "Rekviziti", " ", " " }));

        btnChange.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnChange.setText("Izmeni");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdate.setText("Azuriraj");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSave.setText("Sacuvaj");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBack.setText("←");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnHelp.setText("Pomoc");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnChange))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHelp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSave)
                                .addGap(52, 52, 52)
                                .addComponent(btnUpdate))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 491, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtName)
                                .addGap(195, 195, 195))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(comboType, javax.swing.GroupLayout.Alignment.LEADING, 0, 334, Short.MAX_VALUE)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(comboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(btnChange)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnSave)
                    .addComponent(btnBack)
                    .addComponent(btnHelp))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        error="";
        if(!checkFileds()){
            JOptionPane.showMessageDialog(this, error, "Message", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Article article = new Article();
        article.setName(txtName.getText());
        article.setPrice(Double.parseDouble(txtPrice.getText()));
        article.setType(comboType.getSelectedItem().toString());
        try {
            Article returnArticle=ControllerUI.getInstance().saveArticle(article);
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio artikal");
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti artikal: "+ex.getMessage(), "Message", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        prepareView(FormViewMode.EDIT_MODE);
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        error="";
        if(!checkFileds()){
        JOptionPane.showMessageDialog(this, error, "Message", JOptionPane.ERROR_MESSAGE);
        return;
        }
        Article article = chosenArticle;
        article.setName(txtName.getText());
        article.setPrice(Double.parseDouble(txtPrice.getText()));
        article.setType(comboType.getSelectedItem().toString());
        try {
        Article returnArticle=ControllerUI.getInstance().updateArticle(article);
        JOptionPane.showMessageDialog(this, "Sistem je zapamtio artikal");
        this.dispose();
        } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti artikal: " + ex.getMessage(), "Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        JOptionPane.showMessageDialog(this, "Ovo je forma za prikaz, izmenu i dodavanje aritkala!\n"
                + "Ukoliko se izabere mod za dodavanje artikla na formi su prikazana prazna polja\n"
                + "koja se svamoraju popuniti, nakon cega se validiraju i ukoliko je sve u redu artikal\n"
                + "se dodaje u sistem. Nijedno polje ne sme da bude prazno, dok cena mora biti numericka vrednost\n"
                + "koja je veca od nule. Tip se bira iz opadajuceg menija. Ukoliko je izabran mod za prikaz artikla\n"
                + "podaci o artiklu su prikazani u odgovarajucim poljima. Na dugme izmeni se omogucava da se ta polja izmene\n"
                + "pri cemu vaze gore navedena pravila. Klikom na dugme azuriraj se podaci o artilu azuriraju. Ukoliko zelite da\n"
                + "obrisete artikal to se moze uraditi klikom na dugme izbrisi.");
    }//GEN-LAST:event_btnHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables

    private boolean checkFileds() {
        boolean signal=true;
        if(Validator.getInstance().isEmpty(txtName.getText()) || Validator.getInstance().isEmpty(txtPrice.getText())){
            error+="Nisu popunjena sva polja\n";
            signal = false;
        }
        
        if(Validator.getInstance().isDouble(txtPrice.getText())){
            error+="Nije uneta numericka vrednost za cenu\n";
            signal = false;            
        }else if(Validator.getInstance().isLowerThanZero(Double.parseDouble(txtPrice.getText()))){
                    error+="Cena mora biti veca od 0\n";
                    signal = false;
        }
   
        
        return signal;
    }

    private void prepareView(int formMode) {
        switch (formMode) {
            case FormViewMode.ADD_MODE:
                btnChange.setEnabled(false);
                btnSave.setEnabled(true);
                btnUpdate.setEnabled(false);
                txtName.setEditable(true);
                txtPrice.setEditable(true);
                comboType.setEnabled(true);
                break;
            case FormViewMode.VIEW_MODE:
                btnChange.setEnabled(true);
                btnSave.setEnabled(false);
                btnUpdate.setEnabled(false);
                txtName.setEditable(false);
                txtPrice.setEditable(false);
                comboType.setEnabled(false);
                break;
            case FormViewMode.EDIT_MODE:
                btnChange.setEnabled(false);
                btnSave.setEnabled(false);
                btnUpdate.setEnabled(true);
                txtName.setEditable(true);
                txtPrice.setEditable(true);
                comboType.setEnabled(true);
                break;
            default:
                throw new AssertionError();
        }
    }

    private void setArticle() {
        txtName.setText(chosenArticle.getName());
        txtPrice.setText(String.valueOf(chosenArticle.getPrice()));
        comboType.setSelectedItem(chosenArticle.getType());
    }
    
    
}
